version: "3.8"

services:
  bot:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - bot.env
    links:
      - "db:db"

  db:
    image: postgres
    restart: always
    env_file:
      - db.env
    volumes:
      - evil-data:/var/lib/postgresql/data

volumes:
  evil-data:
