version: "3.8"

services:
  bot:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - bot.env
    environment:
      - SPRING_REDIS_HOST=redis
    links:
      - "db:db"
      - "redis:redis"

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - evil-data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always

volumes:
  evil-data:
